### ISSUE TITLE
Uncaught Package not found inferno-component.

### ISSUE THREAD

**Issue by dessalines** [nimbusec-oss/inferno-i18next#2]
I get this when using this version that updated recently.

```
ncaught Package not found inferno-component app.js:65925:1395
    u app.js:65925
    c app.js:65925
    require app.js:65925
    <anonymous> inferno-i18next@1.0.1:5
    <anonymous> inferno-i18next@1.0.1:8
    c app.js:65925
    require app.js:65925
    <anonymous> index.tsx:3
    c app.js:65925
    import app.js:65925
    <anonymous> app.js:65922
    <anonymous> app.js:65925
```

The old one at `nimbussec-oss` works fine.

**Comment by bernhardreisenberger** [comment]
Hi dessalines.

i have found your issue. You are using an outdated version of inferno-i18next listed on https://www.npmjs.com/package/inferno-i18next. This version is from Midnite Ninja Innovations and not compatible with the latest inferno.
We have forked that version and made it compatible.
You have to update your package.json with the following entry:
replace `"inferno-i18next": "^1.0.1"` with
`"inferno-i18next": "github:nimbusec-oss/inferno-i18next"`
If you want to use a specific release replace it with `"inferno-i18next": "github:nimbusec-oss/inferno-i18next#semver:^7.4.2"`

All releases made by us, are listed here: https://github.com/nimbusec-oss/inferno-i18next/releases

have a nice weekend

**Comment by dessalines** [comment]
That did it, thanks!

You might wanna change the README, as it gives the wrong install instructions.
